import json

# Full Statutory Master Data: 234 Tamil Nadu Assembly Constituencies
AC_RAW = [
    # Tiruvallur (1-10)
    (1, "Gummidipoondi", "கும்மிடிப்பூண்டி", "Tiruvallur", ["gummidipoondi", "கும்மிடிப்பூண்டி"]),
    (2, "Ponneri", "பொன்னேரி", "Tiruvallur", ["ponneri", "பொன்னேரி"]),
    (3, "Tiruttani", "திருத்தணி", "Tiruvallur", ["tiruttani", "திருத்தணி"]),
    (4, "Thiruvallur", "திருவள்ளூர்", "Tiruvallur", ["thiruvallur", "tiruvallur", "திருவள்ளூர்"]),
    (5, "Poonamallee", "பூந்தமல்லி", "Tiruvallur", ["poonamallee", "பூந்தமல்லி"]),
    (6, "Avadi", "ஆவடி", "Tiruvallur", ["avadi", "ஆவடி"]),
    # Chennai (7-22)
    (7, "Maduravoyal", "மதுரவாயல்", "Chennai", ["maduravoyal", "மதுரவாயல்"]),
    (8, "Ambattur", "அம்பத்தூர்", "Chennai", ["ambattur", "அம்பத்தூர்"]),
    (9, "Madavaram", "மாதவரம்", "Chennai", ["madavaram", "மாதவரம்"]),
    (10, "Thiruvottiyur", "திருவொற்றியூர்", "Chennai", ["thiruvottiyur", "tiruvottiyur", "திருவொற்றியூர்"]),
    (11, "Dr. Radhakrishnan Nagar", "ராதாகிருஷ்ணன் நகர்", "Chennai", ["rk nagar", "r.k. nagar", "radhakrishnan nagar", "ஆர்.கே.நகர்"]),
    (12, "Perambur", "பெரம்பூர்", "Chennai", ["perambur", "பெரம்பூர்"]),
    (13, "Kolathur", "கொளத்தூர்", "Chennai", ["kolathur", "கொளத்தூர்"]),
    (14, "Villivakkam", "வில்லிவாக்கம்", "Chennai", ["villivakkam", "வில்லிவாக்கம்"]),
    (15, "Thiru-Vi-Ka-Nagar", "திருவிக நகர்", "Chennai", ["thiru-vi-ka-nagar", "thiru vi ka nagar", "திருவிக நகர்"]),
    (16, "Egmore", "எழும்பூர்", "Chennai", ["egmore", "எழும்பூர்"]),
    (17, "Royapuram", "இராயபுரம்", "Chennai", ["royapuram", "ராயபுரம்", "இராயபுரம்"]),
    (18, "Harbour", "துறைமுகம்", "Chennai", ["harbour", "ஹார்பர்", "துறைமுகம்", "broadway", "george town"]),
    (19, "Chepauk-Thiruvallikeni", "சேப்பாக்கம்-திருவல்லிக்கேணி", "Chennai", ["chepauk", "triplicane", "சேப்பாக்கம்", "திருவல்லிக்கேணி"]),
    (20, "Thousand Lights", "ஆயிரம் விளக்கு", "Chennai", ["thousand lights", "ஆயிரம் விளக்கு"]),
    (21, "Anna Nagar", "அண்ணா நகர்", "Chennai", ["anna nagar", "அண்ணா நகர்"]),
    (22, "Virugampakkam", "விருகம்பாக்கம்", "Chennai", ["virugampakkam", "விருகம்பாக்கம்"]),
    (23, "Saidapet", "சைதாப்பேட்டை", "Chennai", ["saidapet", "சைதாப்பேட்டை"]),
    (24, "Thiyagarayanagar", "தியாகராய நகர்", "Chennai", ["t nagar", "t. nagar", "thiyagaraya nagar", "தி நகர்", "தியாகராய நகர்"]),
    (25, "Mylapore", "மயிலாப்பூர்", "Chennai", ["mylapore", "மயிலாப்பூர்", "mandaveli", "alwarpet"]),
    (26, "Velachery", "வேளச்சேரி", "Chennai", ["velachery", "வேளச்சேரி", "taramani"]),
    # Chengalpattu / Kancheepuram (27-37)
    (27, "Shozhinganallur", "சோழிங்கநல்லூர்", "Chengalpattu", ["sholinganallur", "shozhinganallur", "சோழிங்கநல்லூர்", "omr"]),
    (28, "Alandur", "ஆலந்தூர்", "Kancheepuram", ["alandur", "ஆலந்தூர்", "guindy"]),
    (29, "Sriperumbudur", "ஸ்ரீபெரும்புதூர்", "Kancheepuram", ["sriperumbudur", "ஸ்ரீபெரும்புதூர்"]),
    (30, "Pallavaram", "பல்லாவரம்", "Chengalpattu", ["pallavaram", "பல்லாவரம்", "chromepet"]),
    (31, "Tambaram", "தாம்பரம்", "Chengalpattu", ["tambaram", "தாம்பரம்"]),
    (32, "Chengalpattu", "செங்கல்பட்டு", "Chengalpattu", ["chengalpattu", "செங்கல்பட்டு"]),
    (33, "Thiruporur", "திருப்போரூர்", "Chengalpattu", ["thiruporur", "திருப்போரூர்", "kelambakkam"]),
    (34, "Cheyyur", "செய்யூர்", "Chengalpattu", ["cheyyur", "செய்யூர்"]),
    (35, "Madurantakam", "மதுராந்தகம்", "Chengalpattu", ["madurantakam", "மதுராந்தகம்", "achirupakkam"]),
    (36, "Uthiramerur", "உத்திரமேரூர்", "Kancheepuram", ["uthiramerur", "உத்திரமேரூர்"]),
    (37, "Kancheepuram", "காஞ்சிபுரம்", "Kancheepuram", ["kancheepuram", "kanchipuram", "காஞ்சிபுரம்"]),
    # Ranipet / Vellore / Tirupathur (38-50)
    (38, "Arakkonam", "அரக்கோணம்", "Ranipet", ["arakkonam", "அரக்கோணம்"]),
    (39, "Sholingur", "சோளிங்கர்", "Ranipet", ["sholingur", "சோளிங்கர்"]),
    (40, "Katpadi", "காட்பாடி", "Vellore", ["katpadi", "காட்பாடி"]),
    (41, "Ranipet", "ராணிப்பேட்டை", "Ranipet", ["ranipet", "ராணிப்பேட்டை"]),
    (42, "Arcot", "ஆற்காடு", "Ranipet", ["arcot", "ஆற்காடு"]),
    (43, "Vellore", "வேலூர்", "Vellore", ["vellore", "வேலூர்"]),
    (44, "Anaikattu", "அணைக்கட்டு", "Vellore", ["anaikattu", "அணைக்கட்டு"]),
    (45, "Kilvaithinankuppam", "கே.வி.குப்பம்", "Vellore", ["kv kuppam", "kilvaithinankuppam", "கே.வி.குப்பம்"]),
    (46, "Gudiyattam", "குடியாத்தம்", "Vellore", ["gudiyattam", "குடியாத்தம்"]),
    (47, "Vaniyambadi", "வாணியம்பாடி", "Tirupathur", ["vaniyambadi", "வாணியம்பாடி"]),
    (48, "Ambur", "ஆம்பூர்", "Tirupathur", ["ambur", "ஆம்பூர்"]),
    (49, "Jolarpet", "ஜோலார்பேட்டை", "Tirupathur", ["jolarpet", "ஜோலார்பேட்டை"]),
    (50, "Tirupattur", "திருப்பத்தூர்", "Tirupathur", ["tirupattur", "திருப்பத்தூர்"]),
    # Krishnagiri / Dharmapuri (51-61)
    (51, "Uthangarai", "ஊத்தங்கரை", "Krishnagiri", ["uthangarai", "ஊத்தங்கரை"]),
    (52, "Bargur", "பர்கூர்", "Krishnagiri", ["bargur", "பர்கூர்"]),
    (53, "Krishnagiri", "கிருஷ்ணகிரி", "Krishnagiri", ["krishnagiri", "கிருஷ்ணகிரி"]),
    (54, "Veppanahalli", "வேப்பனஹள்ளி", "Krishnagiri", ["veppanahalli", "வேப்பனஹள்ளி"]),
    (55, "Hosur", "ஓசூர்", "Krishnagiri", ["hosur", "ஓசூர்"]),
    (56, "Thalli", "தளி", "Krishnagiri", ["thalli", "தளி"]),
    (57, "Palacode", "பாலக்கோடு", "Dharmapuri", ["palacode", "பாலக்கோடு"]),
    (58, "Pennagaram", "பெPennagaram", "Dharmapuri", ["pennagaram", "பெPennagaram", "hogenakkal"]),
    (59, "Dharmapuri", "தருமபுரி", "Dharmapuri", ["dharmapuri", "தருமபுரி"]),
    (60, "Pappireddippatti", "பாப்பிரெட்டிப்பட்டி", "Dharmapuri", ["pappireddippatti", "பாப்பிரெட்டிப்பட்டி"]),
    (61, "Harur", "அரூர்", "Dharmapuri", ["harur", "அரூர்"]),
    # Tiruvannamalai / Viluppuram / Kallakurichi (62-80)
    (62, "Chengam", "செங்கம்", "Tiruvannamalai", ["chengam", "செங்கம்"]),
    (63, "Tiruvannamalai", "திருவண்ணாமலை", "Tiruvannamalai", ["tiruvannamalai", "திருவண்ணாமலை"]),
    (64, "Kilpennathur", "கீழ்பெPennathur", "Tiruvannamalai", ["kilpennathur", "கீழ்பெPennathur"]),
    (65, "Kalasapakkam", "கலசப்பாக்கம்", "Tiruvannamalai", ["kalasapakkam", "கலசப்பாக்கம்"]),
    (66, "Polur", "போளூர்", "Tiruvannamalai", ["polur", "போளூர்"]),
    (67, "Arani", "ஆரணி", "Tiruvannamalai", ["arani", "ஆரணி"]),
    (68, "Cheyyar", "செய்யாறு", "Tiruvannamalai", ["cheyyar", "செய்யாறு"]),
    (69, "Vandavasi", "வந்தவாசி", "Tiruvannamalai", ["vandavasi", "வந்தவாசி"]),
    (70, "Gingee", "செஞ்சி", "Viluppuram", ["gingee", "செஞ்சி"]),
    (71, "Mailam", "மயிலம்", "Viluppuram", ["mailam", "மயிலம்"]),
    (72, "Tindivanam", "திண்டிவனம்", "Viluppuram", ["tindivanam", "திண்டிவனம்"]),
    (73, "Vanur", "வானூர்", "Viluppuram", ["vanur", "வானூர்"]),
    (74, "Viluppuram", "விழுப்புரம்", "Viluppuram", ["viluppuram", "villupuram", "விழுப்புரம்"]),
    (75, "Vikravandi", "விக்ரவாண்டி", "Viluppuram", ["vikravandi", "விக்ரவாண்டி"]),
    (76, "Tirukkoyilur", "திருக்கோவிலூர்", "Kallakurichi", ["tirukkoyilur", "திருக்கோவிலூர்"]),
    (77, "Ulundurpettai", "உளுந்தூர்பேட்டை", "Kallakurichi", ["ulundurpet", "ulundurpettai", "உளுந்தூர்பேட்டை"]),
    (78, "Rishivandiyam", "ரிஷிவந்தியம்", "Kallakurichi", ["rishivandiyam", "ரிஷிவந்தியம்"]),
    (79, "Sankarapuram", "சங்கராபுரம்", "Kallakurichi", ["sankarapuram", "சங்கராபுரம்"]),
    (80, "Kallakurichi", "கள்ளக்குறிச்சி", "Kallakurichi", ["kallakurichi", "கள்ளக்குறிச்சி"]),
    # Salem / Namakkal (81-95)
    (81, "Gangavalli", "கங்கவல்லி", "Salem", ["gangavalli", "கங்கவல்லி"]),
    (82, "Attur", "ஆத்தூர்", "Salem", ["attur", "ஆத்தூர்"]),
    (83, "Yercaud", "ஏற்காடு", "Salem", ["yercaud", "ஏற்காடு"]),
    (84, "Omalur", "ஓமலூர்", "Salem", ["omalur", "ஓமலூர்"]),
    (85, "Mettur", "மேட்டூர்", "Salem", ["mettur", "மேட்டூர்"]),
    (86, "Edappadi", "எடப்பாடி", "Salem", ["edappadi", "எடப்பாடி"]),
    (87, "Sankari", "சங்ககிரி", "Salem", ["sankari", "சங்ககிரி"]),
    (88, "Salem (West)", "சேலம் (மேற்கு)", "Salem", ["salem west", "சேலம் மேற்கு"]),
    (89, "Salem (North)", "சேலம் (வடக்கு)", "Salem", ["salem north", "சேலம் வடக்கு"]),
    (90, "Salem (South)", "சேலம் (தெற்கு)", "Salem", ["salem south", "சேலம் தெற்கு"]),
    (91, "Veerapandi", "வீரபாண்டி", "Salem", ["veerapandi", "வீரபாண்டி"]),
    (92, "Rasipuram", "ராசிபுரம்", "Namakkal", ["rasipuram", "ராசிபுரம்"]),
    (93, "Senthamangalam", "சேந்தமங்கலம்", "Namakkal", ["senthamangalam", "சேந்தமங்கலம்"]),
    (94, "Namakkal", "நாமக்கல்", "Namakkal", ["namakkal", "நாமக்கல்"]),
    (95, "Paramathi-Velur", "பரமத்தி-வேலூர்", "Namakkal", ["paramathi velur", "பரமத்தி வேலூர்"]),
    (96, "Tiruchengodu", "திருச்செங்கோடு", "Namakkal", ["tiruchengodu", "திருச்செங்கோடு"]),
    (97, "Kumarapalayam", "குமாரபாளையம்", "Namakkal", ["kumarapalayam", "குமாரபாளையம்"]),
    # Erode / Nilgiris / Coimbatore / Tiruppur (98-126)
    (98, "Erode (East)", "ஈரோடு (கிழக்கு)", "Erode", ["erode east", "ஈரோடு கிழக்கு"]),
    (99, "Erode (West)", "ஈரோடு (மேற்கு)", "Erode", ["erode west", "ஈரோடு மேற்கு"]),
    (100, "Modakkurichi", "மொடக்குறிச்சி", "Erode", ["modakkurichi", "மொடக்குறிச்சி"]),
    (101, "Dharapuram", "தாராபுரம்", "Tiruppur", ["dharapuram", "தாராபுரம்"]),
    (102, "Kangayam", "காங்கேயம்", "Tiruppur", ["kangayam", "காங்கேயம்"]),
    (103, "Perundurai", "பெருந்துறை", "Erode", ["perundurai", "பெருந்துறை"]),
    (104, "Bhavani", "பவானி", "Erode", ["bhavani", "பவானி"]),
    (105, "Anthiyur", "அந்தியூர்", "Erode", ["anthiyur", "அந்தியூர்"]),
    (106, "Gobichettipalayam", "கோபிசெட்டிபாளையம்", "Erode", ["gobichettipalayam", "gobi", "கோபி"]),
    (107, "Bhavanisagar", "பவானிசாகர்", "Erode", ["bhavanisagar", "பவானிசாகர்"]),
    (108, "Udhagamandalam", "உதகமண்டலம்", "Nilgiris", ["ooty", "udhagamandalam", "ஊட்டி"]),
    (109, "Gudalur", "கூடலூர்", "Nilgiris", ["gudalur", "கூடலூர்"]),
    (110, "Coonoor", "குன்னூர்", "Nilgiris", ["coonoor", "குன்னூர்"]),
    (111, "Mettupalayam", "மேட்டுப்பாளையம்", "Coimbatore", ["mettupalayam", "மேட்டுப்பாளையம்"]),
    (112, "Avanashi", "அவினாசி", "Tiruppur", ["avanashi", "அவினாசி"]),
    (113, "Tiruppur (North)", "திருப்பூர் (வடக்கு)", "Tiruppur", ["tiruppur north", "திருப்பூர் வடக்கு"]),
    (114, "Tiruppur (South)", "திருப்பூர் (தெற்கு)", "Tiruppur", ["tiruppur south", "திருப்பூர் தெற்கு"]),
    (115, "Palladam", "பல்லடம்", "Tiruppur", ["palladam", "பல்லடம்"]),
    (116, "Sulur", "சூலூர்", "Coimbatore", ["sulur", "சூலூர்"]),
    (117, "Kavundampalayam", "கவுண்டம்பாளையம்", "Coimbatore", ["kavundampalayam", "கவுண்டம்பாளையம்"]),
    (118, "Coimbatore (North)", "கோவை (வடக்கு)", "Coimbatore", ["coimbatore north", "கோவை வடக்கு"]),
    (119, "Thondamuthur", "தொண்டாமுத்தூர்", "Coimbatore", ["thondamuthur", "தொண்டாமுத்தூர்"]),
    (120, "Coimbatore (South)", "கோவை (தெற்கு)", "Coimbatore", ["coimbatore south", "கோவை தெற்கு"]),
    (121, "Singanallur", "சிங்காநல்லூர்", "Coimbatore", ["singanallur", "சிங்காநல்லூர்"]),
    (122, "Kinathukadavu", "கிணத்துக்கடவு", "Coimbatore", ["kinathukadavu", "கிணத்துக்கடவு"]),
    (123, "Pollachi", "பொள்ளாச்சி", "Coimbatore", ["pollachi", "பொள்ளாச்சி"]),
    (124, "Valparai", "வால்பாறை", "Coimbatore", ["valparai", "வால்பாறை"]),
    (125, "Udumalaipettai", "உடுமலைப்பேட்டை", "Tiruppur", ["udumalaipettai", "உடுமலை"]),
    (126, "Madathukulam", "மடத்துக்குளம்", "Tiruppur", ["madathukulam", "மடத்துக்குளம்"]),
    # Dindigul / Theni / Karur (127-142)
    (127, "Palani", "பழனி", "Dindigul", ["palani", "பழனி"]),
    (128, "Oddanchatram", "ஒட்டன்சத்திரம்", "Dindigul", ["oddanchatram", "ஒட்டன்சத்திரம்"]),
    (129, "Athoor", "ஆத்தூர்-திண்டுக்கல்", "Dindigul", ["athoor", "ஆத்தூர் திண்டுக்கல்"]),
    (130, "Nilakkottai", "நிலக்கோட்டை", "Dindigul", ["nilakkottai", "நிலக்கோட்டை"]),
    (131, "Natham", "நத்தம்", "Dindigul", ["natham", "நத்தம்"]),
    (132, "Dindigul", "திண்டுக்கல்", "Dindigul", ["dindigul", "திண்டுக்கல்"]),
    (133, "Vedasandur", "வேடசந்தூர்", "Dindigul", ["vedasandur", "வேடசந்தூர்"]),
    (134, "Aravakurichi", "அரவக்குறிச்சி", "Karur", ["aravakurichi", "அரவக்குறிச்சி"]),
    (135, "Karur", "கரூர்", "Karur", ["karur", "கரூர்"]),
    (136, "Krishnarayapuram", "கிருஷ்ணராயபுரம்", "Karur", ["krishnarayapuram", "கிருஷ்ணராயபுரம்"]),
    (137, "Kulithalai", "குளித்தலை", "Karur", ["kulithalai", "குளித்தலை"]),
    (138, "Manappaarai", "மணப்பாறை", "Tiruchirappalli", ["manapparai", "மணப்பாறை"]),
    (139, "Srirangam", "ஸ்ரீரங்கம்", "Tiruchirappalli", ["srirangam", "ஸ்ரீரங்கம்"]),
    (140, "Tiruchirappalli (West)", "திருச்சிராப்பள்ளி (மேற்கு)", "Tiruchirappalli", ["trichy west", "திருச்சி மேற்கு"]),
    (141, "Tiruchirappalli (East)", "திருச்சிராப்பள்ளி (கிழக்கு)", "Tiruchirappalli", ["trichy east", "திருச்சி கிழக்கு"]),
    (142, "Thiruverumbur", "திருவெறும்பூர்", "Tiruchirappalli", ["thiruverumbur", "திருவெறும்பூர்"]),
    (143, "Lalgudi", "லால்குடி", "Tiruchirappalli", ["lalgudi", "லால்குடி"]),
    (144, "Manachanallur", "மண்ணச்சநல்லூர்", "Tiruchirappalli", ["manachanallur", "மண்ணச்சநல்லூர்"]),
    (145, "Musiri", "முசிறி", "Tiruchirappalli", ["musiri", "முசிறி"]),
    (146, "Thuraiyur", "துறையூர்", "Tiruchirappalli", ["thuraiyur", "துறையூர்"]),
    (147, "Perambalur", "பெரம்பலூர்", "Perambalur", ["perambalur", "பெரம்பலூர்"]),
    (148, "Kunnam", "குன்னம்", "Perambalur", ["kunnam", "குன்னம்"]),
    (149, "Ariyalur", "அரியலூர்", "Ariyalur", ["ariyalur", "அரியலூர்"]),
    (150, "Jayankondam", "ஜெயங்கொண்டம்", "Ariyalur", ["jayankondam", "ஜெயங்கொண்டம்"]),
    # Cuddalore / Nagapattinam / Mayiladuthurai / Tiruvarur / Thanjavur (151-176)
    (151, "Tittakudi", "திட்டக்குடி", "Cuddalore", ["tittakudi", "திட்டக்குடி"]),
    (152, "Vriddhachalam", "விருத்தாசலம்", "Cuddalore", ["vriddhachalam", "விருத்தாசலம்"]),
    (153, "Neyveli", "நெய்வேலி", "Cuddalore", ["neyveli", "நெய்வேலி"]),
    (154, "Panruti", "பண்ருட்டி", "Cuddalore", ["panruti", "பண்ருட்டி"]),
    (155, "Cuddalore", "கடலூர்", "Cuddalore", ["cuddalore", "கடலூர்"]),
    (156, "Kurinjipadi", "குறிஞ்சிப்பாடி", "Cuddalore", ["kurinjipadi", "குறிஞ்சிப்பாடி"]),
    (157, "Bhuvanagiri", "புவனகிரி", "Cuddalore", ["bhuvanagiri", "புவனகிரி"]),
    (158, "Chidambaram", "சிதம்பரம்", "Cuddalore", ["chidambaram", "சிதம்பரம்"]),
    (159, "Kattumannarkoil", "காட்டுமன்னார்கோயில்", "Cuddalore", ["kattumannarkoil", "காட்டுமன்னார்கோயில்"]),
    (160, "Sirkazhi", "சீர்காழி", "Mayiladuthurai", ["sirkazhi", "சீர்காழி"]),
    (161, "Mayiladuthurai", "மயிலாடுதுறை", "Mayiladuthurai", ["mayiladuthurai", "மயிலாடுதுறை"]),
    (162, "Poompuhar", "பூம்புகார்", "Mayiladuthurai", ["poompuhar", "பூம்புகார்"]),
    (163, "Nagapattinam", "நாகப்பட்டினம்", "Nagapattinam", ["nagapattinam", "நாகப்பட்டினம்"]),
    (164, "Kilvelur", "கீழ்வேளூர்", "Nagapattinam", ["kilvelur", "கீழ்வேளூர்"]),
    (165, "Vedaranyam", "வேதாரண்யம்", "Nagapattinam", ["vedaranyam", "வேதாரண்யம்"]),
    (166, "Thiruthuraipoondi", "திருத்துறைப்பூண்டி", "Tiruvarur", ["thiruthuraipoondi", "திருத்துறைப்பூண்டி"]),
    (167, "Mannargudi", "மன்னார்குடி", "Tiruvarur", ["mannargudi", "மன்னார்குடி"]),
    (168, "Thiruvarur", "திருவாரூர்", "Tiruvarur", ["thiruvarur", "tiruvarur", "திருவாரூர்"]),
    (169, "Nannilam", "நன்னிலம்", "Tiruvarur", ["nannilam", "நன்னிலம்"]),
    (170, "Thiruvidaimarudur", "திருவிடைமருதூர்", "Thanjavur", ["thiruvidaimarudur", "திருவிடைமருதூர்"]),
    (171, "Kumbakonam", "கும்பகோணம்", "Thanjavur", ["kumbakonam", "கும்பகோணம்"]),
    (172, "Papanasam", "பாபநாசம்", "Thanjavur", ["papanasam", "பாபநாசம்"]),
    (173, "Thiruvaiyaru", "திருவையாறு", "Thanjavur", ["thiruvaiyaru", "திருவையாறு"]),
    (174, "Thanjavur", "தஞ்சாவூர்", "Thanjavur", ["thanjavur", "தஞ்சாவூர்"]),
    (175, "Orathanadu", "ஒரத்தநாடு", "Thanjavur", ["orathanadu", "ஒரத்தநாடு"]),
    (176, "Pattukkottai", "பட்டுக்கோட்டை", "Thanjavur", ["pattukkottai", "பட்டுக்கோட்டை"]),
    (177, "Peravurani", "பேராவூரணி", "Thanjavur", ["peravurani", "பேராவூரணி"]),
    # Pudukkottai / Sivaganga / Madurai / Theni (178-203)
    (178, "Gandharvakottai", "கந்தர்வக்கோட்டை", "Pudukkottai", ["gandharvakottai", "கந்தர்வக்கோட்டை"]),
    (179, "Viralimalai", "விராலிமலை", "Pudukkottai", ["viralimalai", "விராலிமலை"]),
    (180, "Pudukkottai", "புதுக்கோட்டை", "Pudukkottai", ["pudukkottai", "புதுக்கோட்டை"]),
    (181, "Thirumayam", "திருமயம்", "Pudukkottai", ["thirumayam", "திருமயம்"]),
    (182, "Alangudi", "ஆலங்குடி", "Pudukkottai", ["alangudi", "ஆலங்குடி"]),
    (183, "Aranthangi", "அறந்தாங்கி", "Pudukkottai", ["aranthangi", "அறந்தாங்கி"]),
    (184, "Karaikudi", "காரைக்குடி", "Sivaganga", ["karaikudi", "காரைக்குடி"]),
    (185, "Tiruppattur (Sivaganga)", "திருப்பத்தூர் (சிவகங்கை)", "Sivaganga", ["tiruppattur sivaganga", "திருப்பத்தூர் சிவகங்கை"]),
    (186, "Sivaganga", "சிவகங்கை", "Sivaganga", ["sivaganga", "சிவகங்கை"]),
    (187, "Manamadurai", "மானாமதுரை", "Sivaganga", ["manamadurai", "மானாமதுரை"]),
    (188, "Melur", "மேலூர்", "Madurai", ["melur", "மேலூர்"]),
    (189, "Madurai East", "மதுரை கிழக்கு", "Madurai", ["madurai east", "மதுரை கிழக்கு"]),
    (190, "Sholavandan", "சோழவந்தான்", "Madurai", ["sholavandan", "சோழவந்தான்"]),
    (191, "Madurai North", "மதுரை வடக்கு", "Madurai", ["madurai north", "மதுரை வடக்கு"]),
    (192, "Madurai South", "மதுரை தெற்கு", "Madurai", ["madurai south", "மதுரை தெற்கு"]),
    (193, "Madurai Central", "மதுரை மத்தி", "Madurai", ["madurai central", "மதுரை மத்தி"]),
    (194, "Madurai West", "மதுரை மேற்கு", "Madurai", ["madurai west", "மதுரை மேற்கு"]),
    (195, "Thiruparankundram", "திருப்பரங்குன்றம்", "Madurai", ["thiruparankundram", "திருப்பரங்குன்றம்"]),
    (196, "Thirumangalam", "திருமங்கலம்", "Madurai", ["thirumangalam", "திருமங்கலம்"]),
    (197, "Usilampatti", "உசிலம்பட்டி", "Madurai", ["usilampatti", "உசிலம்பட்டி"]),
    (198, "Andipatti", "ஆண்டிபட்டி", "Theni", ["andipatti", "ஆண்டிபட்டி"]),
    (199, "Periyakulam", "பெரியகுளம்", "Theni", ["periyakulam", "பெரியகுளம்"]),
    (200, "Bodinayakanur", "போடிநாயக்கனூர்", "Theni", ["bodinayakanur", "bodi", "போடி"]),
    (201, "Cumbum", "கம்பம்", "Theni", ["cumbum", "கம்பம்"]),
    # Virudhunagar / Ramanathapuram / Thoothukudi (202-218)
    (202, "Rajapalayam", "ராஜபாளையம்", "Virudhunagar", ["rajapalayam", "ராஜபாளையம்"]),
    (203, "Srivilliputhur", "ஸ்ரீவில்லிபுத்தூர்", "Virudhunagar", ["srivilliputhur", "ஸ்ரீவில்லிபுத்தூர்"]),
    (204, "Sattur", "சாத்தூர்", "Virudhunagar", ["sattur", "சாத்தூர்"]),
    (205, "Sivakasi", "சிவகாசி", "Virudhunagar", ["sivakasi", "சிவகாசி"]),
    (206, "Virudhunagar", "விருதுநகர்", "Virudhunagar", ["virudhunagar", "விருதுநகர்"]),
    (207, "Aruppukkottai", "அருப்புக்கோட்டை", "Virudhunagar", ["aruppukkottai", "அருப்புக்கோட்டை"]),
    (208, "Tiruchuli", "திருச்சுழி", "Virudhunagar", ["tiruchuli", "திருச்சுழி"]),
    (209, "Paramakudi", "பரமக்குடி", "Ramanathapuram", ["paramakudi", "பரமக்குடி"]),
    (210, "Tiruvadanai", "திருவாடானை", "Ramanathapuram", ["tiruvadanai", "திருவாடானை"]),
    (211, "Ramanathapuram", "ராமநாதபுரம்", "Ramanathapuram", ["ramanathapuram", "ராமநாதபுரம்"]),
    (212, "Mudukulathur", "முதுகுளத்தூர்", "Ramanathapuram", ["mudukulathur", "முதுகுளத்தூர்"]),
    (213, "Vilathikulam", "விளாத்திகுளம்", "Thoothukudi", ["vilathikulam", "விளாத்திகுளம்"]),
    (214, "Thoothukkudi", "தூத்துக்குடி", "Thoothukudi", ["thoothukudi", "tuticorin", "தூத்துக்குடி"]),
    (215, "Tiruchendur", "திருச்செந்தூர்", "Thoothukudi", ["tiruchendur", "திருச்செந்தூர்"]),
    (216, "Srivaikuntam", "ஸ்ரீவைகுண்டம்", "Thoothukudi", ["srivaikuntam", "ஸ்ரீவைகுண்டம்"]),
    (217, "Ottapidaram", "ஒட்டப்பிடாரம்", "Thoothukudi", ["ottapidaram", "ஒட்டப்பிடாரம்"]),
    (218, "Kovilpatti", "கோவில்பட்டி", "Thoothukudi", ["kovilpatti", "கோவில்பட்டி"]),
    # Tenkasi / Tirunelveli / Kanniyakumari (219-234)
    (219, "Sankarankovil", "சங்கரன்கோவில்", "Tenkasi", ["sankarankovil", "சங்கரன்கோவில்"]),
    (220, "Vasudevanallur", "வாசுதேவநல்லூர்", "Tenkasi", ["vasudevanallur", "வாசுதேவநல்லூர்"]),
    (221, "Kadayanallur", "கடையநல்லூர்", "Tenkasi", ["kadayanallur", "கடையநல்லூர்"]),
    (222, "Tenkasi", "தென்காசி", "Tenkasi", ["tenkasi", "தென்காசி"]),
    (223, "Alangulam", "ஆலங்குளம்", "Tenkasi", ["alangulam", "ஆலங்குளம்"]),
    (224, "Tirunelveli", "திருநெல்வேலி", "Tirunelveli", ["tirunelveli", "nellai", "திருநெல்வேலி", "நெல்லை"]),
    (225, "Ambasamudram", "அம்பாசமுத்திரம்", "Tirunelveli", ["ambasamudram", "அம்பாசமுத்திரம்"]),
    (226, "Palayamkottai", "பாளையங்கோட்டை", "Tirunelveli", ["palayamkottai", "பாளையங்கோட்டை"]),
    (227, "Nanguneri", "நாங்குநேரி", "Tirunelveli", ["nanguneri", "நாங்குநேரி"]),
    (228, "Radhapuram", "ராதாபுரம்", "Tirunelveli", ["radhapuram", "ராதாபுரம்"]),
    (229, "Kanniyakumari", "கன்னியாகுமரி", "Kanyakumari", ["kanniyakumari", "kanyakumari", "கன்னியாகுமரி"]),
    (230, "Nagercoil", "நாகர்கோவில்", "Kanyakumari", ["nagercoil", "நாகர்கோவில்"]),
    (231, "Colachal", "குளச்சல்", "Kanyakumari", ["colachal", "குளச்சல்"]),
    (232, "Padmanabhapuram", "பத்மநாபபுரம்", "Kanyakumari", ["padmanabhapuram", "பத்மநாபபுரம்"]),
    (233, "Vilavancode", "விளவங்கோடு", "Kanyakumari", ["vilavancode", "விளவங்கோடு"]),
    (234, "Killiyoor", "கிள்ளியூர்", "Kanyakumari", ["killiyoor", "கிள்ளியூர்"])
]

def main():
    formatted = []
    for item in AC_RAW:
        formatted.append({
            "ac_number": item[0],
            "name": item[1],
            "name_ta": item[2],
            "district": item[3],
            "aliases": item[4]
        })

    with open("tn_234_constituencies.json", "w", encoding="utf-8") as f:
        json.dump(formatted, f, ensure_ascii=False, indent=2)

    print(f"Success! Generated full statutory master: {len(formatted)} Assembly Constituencies into tn_234_constituencies.json")

if __name__ == "__main__":
    main()